using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TelemetryGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class TelemetryGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "Telemetry.Generated.GenerateTelemetryAttribute";

    private static readonly DiagnosticDescriptor TypeMustBePartial = new(
        "TSG001",
        "Telemetry target must be partial",
        "Type '{0}' must be partial so telemetry members can be generated",
        "TelemetryGenerator",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnsupportedTypeShape = new(
        "TSG002",
        "Telemetry target shape is unsupported",
        "Type '{0}' must be a top-level, non-generic type",
        "TelemetryGenerator",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output => output.AddSource(
            "GenerateTelemetryAttribute.g.cs",
            SourceText.From(AttributeSource, Encoding.UTF8)));

        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (syntaxContext, cancellationToken) => CreateTarget(syntaxContext, cancellationToken));

        context.RegisterSourceOutput(targets, static (output, target) =>
        {
            if (!target.IsSupportedShape)
            {
                output.ReportDiagnostic(Diagnostic.Create(
                    UnsupportedTypeShape,
                    target.Location,
                    target.FullyQualifiedName));
                return;
            }

            if (!target.IsPartial)
            {
                output.ReportDiagnostic(Diagnostic.Create(
                    TypeMustBePartial,
                    target.Location,
                    target.FullyQualifiedName));
                return;
            }

            output.AddSource(target.HintName, SourceText.From(Render(target), Encoding.UTF8));
        });
    }

    private static TelemetryTarget CreateTarget(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var declaration = (TypeDeclarationSyntax)context.TargetNode;
        var symbol = (INamedTypeSymbol)context.TargetSymbol;
        var properties = symbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(static property =>
                !property.IsStatic &&
                property.DeclaredAccessibility == Accessibility.Public &&
                property.GetMethod is not null &&
                property.Parameters.Length == 0)
            .OrderBy(static property => property.Name, StringComparer.Ordinal)
            .Select(static property => new TelemetryProperty(
                property.Name,
                property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
            .ToImmutableArray();

        var namespaceName = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();
        var isPartial = declaration.Modifiers.Any(SyntaxKind.PartialKeyword);
        var typeKeyword = declaration switch
        {
            RecordDeclarationSyntax record when record.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword) => "record struct",
            RecordDeclarationSyntax => "record",
            StructDeclarationSyntax => "struct",
            _ => "class"
        };

        cancellationToken.ThrowIfCancellationRequested();
        return new(
            namespaceName,
            symbol.Name,
            symbol.ToDisplayString(),
            typeKeyword,
            isPartial,
            symbol.ContainingType is null && symbol.Arity == 0,
            declaration.Identifier.GetLocation(),
            properties,
            SanitizeHintName(symbol));
    }

    private static string Render(TelemetryTarget target)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        if (target.NamespaceName is not null)
        {
            builder.Append("namespace ").Append(target.NamespaceName).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("partial ").Append(target.TypeKeyword).Append(' ').Append(target.TypeName).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    public global::System.Collections.Generic.IReadOnlyDictionary<string, object?> ToTelemetry() =>");
        builder.AppendLine("        new global::System.Collections.Generic.Dictionary<string, object?>");
        builder.AppendLine("        {");
        foreach (var property in target.Properties)
        {
            builder.Append("            [\"").Append(property.Name).Append("\"] = ").Append(property.Name).AppendLine(",");
        }

        builder.AppendLine("        };");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string SanitizeHintName(INamedTypeSymbol symbol)
    {
        var name = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var builder = new StringBuilder(name.Length);
        foreach (var character in name)
        {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return builder.Append(".Telemetry.g.cs").ToString();
    }

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace Telemetry.Generated;

        [global::System.AttributeUsage(
            global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct,
            AllowMultiple = false,
            Inherited = false)]
        internal sealed class GenerateTelemetryAttribute : global::System.Attribute;
        """;

    private sealed record TelemetryTarget(
        string? NamespaceName,
        string TypeName,
        string FullyQualifiedName,
        string TypeKeyword,
        bool IsPartial,
        bool IsSupportedShape,
        Location Location,
        ImmutableArray<TelemetryProperty> Properties,
        string HintName);

    private sealed record TelemetryProperty(string Name, string TypeName);
}
