<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ArchitectureBoundaryLab.Application/ArchitectureBoundaryLab.Application.csproj" />
    <ProjectReference Include="../ArchitectureBoundaryLab.Infrastructure/ArchitectureBoundaryLab.Infrastructure.csproj" />
  </ItemGroup>
</Project>
